### ISSUE TITLE
Change message when export is already running

### ISSUE THREAD

**Issue by ernestothorp** [globocom/GloboDNS#6]
Change from: 
"There are another process running"

To:
"There is another process running"
OR
"There are other processes running"

**Comment by AugustooRibeiroo** [comment]
This problem occurs because the GloboDNS has a line in the schedulers table "locked".

Solution:
Run the following command in GloboDNS
Note: when performing the steps you are taking full responsibility

mysql -u root -p

#type the password

show database;

use globodns;

show tables;

select * from schedules;

# Will see a line like the one below
# | 2 | export | 06.02.2016 13:06:04 | 06.01.2016 20:46:33 | 06.02.2016 13:06:04 |
# + ---- + ---------- + --------------------- + ---------- ----------- + --------------------- +

delete from schedules where id = 2;

# Instead of "2" enter the number of your line

After these steps the problem is solved.

**Comment by ernestothorp** [comment]
Augusto,
This issue was just about a spelling error.
You must not delete entries from schedules table, unless the export process was killed.
